# Generated by Django 5.1.1 on 2024-09-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=5)),
                ('agg_method', models.CharField(choices=[('sum', 'Summary'), ('mead', 'Mean'), ('diff', 'Diffrence')], default='sum', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.CharField(choices=[('BEARER', 'BEARER')], default='BEARER', max_length=10)),
                ('rest_api_url', models.CharField(help_text='http://IP_ADDRESS:8123/api/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agg_datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.aggregateddata')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedDataNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('display_history', models.BooleanField(default=False)),
                ('display_unit', models.BooleanField(default=True)),
                ('agg_datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruene_cms.aggregateddata')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='data_sources',
            field=models.ManyToManyField(to='gruene_cms.datasource'),
        ),
    ]
