# Generated by Django 5.1.1 on 2024-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='json_attr',
            field=models.CharField(blank=True, help_text='For HomeAssistant use "state"', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='value_convert',
            field=models.CharField(choices=[('float', 'Float'), ('int', 'Int'), ('text', 'Text')], default='float', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='rest_api_url',
            field=models.CharField(help_text='http://IP_ADDRESS:8123/api/states/sensor.helper_pv_sum_yaml', max_length=255),
        ),
    ]
