# Generated by Django 5.1.1 on 2024-09-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('filer', '0017_image__transparent'),
        ('gruene_cms', '0002_datasource_json_attr_datasource_value_convert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateddata',
            name='agg_method',
            field=models.CharField(choices=[('sum', 'Summary'), ('mead', 'Mean')], default='sum', max_length=10),
        ),
        migrations.CreateModel(
            name='GrueneCMSImageBackgroundNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('background_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.file')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
