# Generated by Django 5.1.1 on 2024-09-30 12:43

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0003_alter_aggregateddata_agg_method_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrueneCMSAnimateTypingNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('pre_text', models.CharField(blank=True, max_length=255, null=True)),
                ('animated_text', models.CharField(blank=True, help_text='Separated by |. i.e. "bla1!bla2!bla3!"', max_length=500, null=True)),
                ('post_text', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_animation', models.BooleanField(default=True)),
                ('type_speed', models.PositiveIntegerField(default=200, help_text='Type speed in ms')),
                ('type_delay', models.PositiveIntegerField(default=1200, help_text='Type delay in ms')),
                ('remove_speed', models.PositiveIntegerField(default=30, help_text='Remove speed in ms')),
                ('remove_delay', models.PositiveIntegerField(default=1500, help_text='Remove delay in ms')),
                ('cursor_speed', models.PositiveIntegerField(default=500, help_text='Cursor speed in ms')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='gruenecmsimagebackgroundnode',
            name='background_image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
