# Generated by Django 5.1.1 on 2024-10-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0004_gruenecmsanimatetypingnode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitUserGroupNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('logged_in', models.BooleanField(default=True)),
                ('logged_in_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
