# Generated by Django 5.1.1 on 2024-10-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0005_limitusergroupnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFormNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('display_form', models.BooleanField(default=True)),
                ('display_greeting', models.BooleanField(default=True)),
                ('display_button', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ChartJSNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('chart_title', models.CharField(max_length=100)),
                ('chart_width', models.PositiveIntegerField(default=500)),
                ('chart_height', models.PositiveIntegerField(default=500)),
                ('dataset_label', models.CharField(max_length=100)),
                ('agg_datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruene_cms.aggregateddata')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
