# Generated by Django 5.1.1 on 2024-10-06 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0006_loginformnode_chartjsnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('edit_groups', models.ManyToManyField(blank=True, related_name='calendar_edit_groups_set', to='auth.group')),
                ('visible_groups', models.ManyToManyField(blank=True, related_name='calendar_visible_groups_set', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_from', models.DateTimeField()),
                ('dt_until', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('max_entries', models.PositiveIntegerField(default=5)),
                ('history_entries_days', models.PositiveIntegerField(default=0)),
                ('show_more_button', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.calendar')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
