# Generated by Django 5.1.1 on 2024-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0007_calendar_calendaritem_calendarnode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarnode',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendarnode',
            name='calendars',
            field=models.ManyToManyField(related_name='calendar_calendarnode_set', to='gruene_cms.calendar'),
        ),
        migrations.AddField(
            model_name='calendarnode',
            name='labeled_calendars',
            field=models.ManyToManyField(blank=True, related_name='calendar_labeled_set', to='gruene_cms.calendar'),
        ),
    ]
