# Generated by Django 5.1.1 on 2024-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0008_remove_calendarnode_calendar_calendarnode_calendars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarnode',
            name='render_template',
            field=models.CharField(choices=[('default', 'Default'), ('table', 'Table'), ('table_editable', 'Table (editable)')], default='default', max_length=255),
        ),
    ]
