# Generated by Django 5.1.1 on 2024-10-06 14:25

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0009_calendarnode_render_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('subtitle', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('keywords', models.CharField(max_length=255)),
                ('summary', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('content', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('published_from', models.DateTimeField()),
                ('published_until', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='gruene_cms.category')),
            ],
        ),
        migrations.CreateModel(
            name='NewsListNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('render_template', models.CharField(choices=[('tiles', 'Tiles, Image and Summary'), ('table', 'Table, Image and Summary'), ('full', 'Full')], default='tiles', max_length=20)),
                ('max_entries', models.PositiveIntegerField(default=10)),
                ('show_outdated', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='gruene_cms.category')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
