# Generated by Django 5.1.1 on 2024-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0012_remove_editoranimatetypingnode_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruenecmsanimatetypingnode',
            name='post_text',
        ),
        migrations.RemoveField(
            model_name='gruenecmsanimatetypingnode',
            name='pre_text',
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='animated_text',
            field=models.CharField(default='Text1|Text2|Text3|', help_text='Separated by |. i.e. "bla1|bla2|bla3|"', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EditorAnimateTypingNode',
        ),
    ]
