# Generated by Django 5.1.1 on 2024-10-06 16:19

import filer.fields.multistorage_file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0013_remove_gruenecmsanimatetypingnode_post_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='attachments',
            field=filer.fields.multistorage_file.MultiStorageFileField(blank=True, upload_to=filer.fields.multistorage_file.generate_filename_multistorage),
        ),
    ]
