# Generated by Django 5.1.1 on 2024-10-06 16:44

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0014_newsitem_attachments'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='attachments',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='insert_images',
            field=models.CharField(choices=[('inside-hr', 'Inside HRs'), ('replace-marker', 'Replace Marker')], default='inside-hr', max_length=255),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=5)),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.newsitem')),
            ],
        ),
    ]
