# Generated by Django 5.1.1 on 2024-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0015_remove_newsitem_attachments_newsitem_insert_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
