# Generated by Django 5.1.1 on 2024-10-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0016_newsitem_content_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='news_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
    ]
