# Generated by Django 5.1.1 on 2024-10-07 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0019_gruenecmsimagebackgroundnode_background_pos_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='newsfeedreader_external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NewsFeedReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.category')),
            ],
        ),
        migrations.AddField(
            model_name='newsitem',
            name='newsfeedreader_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.newsfeedreader'),
        ),
    ]
