# Generated by Django 5.1.1 on 2024-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0020_newsitem_newsfeedreader_external_link_newsfeedreader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='title_h',
            field=models.IntegerField(choices=[(1, 'h1'), (2, 'h2'), (3, 'h3'), (4, 'h4')], default=3),
        ),
    ]
