# Generated by Django 5.1.1 on 2024-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0022_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='instance namespace')),
                ('paginate_by', models.PositiveIntegerField(default=5, verbose_name='paginate size')),
                ('render_template', models.CharField(choices=[('detail', 'Detail with Inline Images'), ('detail_img_content', 'Detail with Images-Col and Content-Col'), ('detail_content_img', 'Detail with Content-Col and Images-Col'), ('detail_img_then_content', 'Detail with Images-Row then Content-Row')], default='detail', max_length=100)),
            ],
        ),
    ]
