# Generated by Django 5.1.1 on 2024-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0023_newspageconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarnode',
            name='render_template',
            field=models.CharField(choices=[('default', 'Default'), ('table', 'Table'), ('table2', 'Table 2 (without head)'), ('table_editable', 'Table (editable)')], default='default', max_length=255),
        ),
    ]
