# Generated by Django 5.1.1 on 2024-10-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0024_alter_calendarnode_render_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendaritem',
            name='linked_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruene_cms.newsitem'),
        ),
        migrations.AddField(
            model_name='calendaritem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
        migrations.AddField(
            model_name='calendarnode',
            name='linked_news_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
    ]
