# Generated by Django 5.1.1 on 2024-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0025_calendaritem_full_day_calendaritem_linked_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='extra_col_classes',
            field=models.CharField(blank=True, help_text='Example: "col-12" or "col-12 col-sm-6 col-md-6 col-lg-12 col-xl-12 col-xxl-12" for two-col for small screens', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newslistnode',
            name='extra_row_classes',
            field=models.CharField(blank=True, help_text='Example: "mb-3"', max_length=255, null=True),
        ),
    ]
