# Generated by Django 5.1.1 on 2024-10-10 13:12

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0026_newslistnode_extra_col_classes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('assigned_to_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.category')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.taskitem')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit_own_tasks', models.BooleanField(default=False)),
                ('render_template', models.CharField(choices=[('list', 'Task List'), ('list_with_assignments', 'Task List (with assignments)'), ('summary', 'Summary my Tasks')], default='list', max_length=40)),
                ('categories', models.ManyToManyField(to='gruene_cms.category')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
