# Generated by Django 5.1.1 on 2024-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0027_taskitem_taskcomment_tasknode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Warning'), (2, 'Danger')], default=0),
        ),
    ]
