# Generated by Django 5.1.1 on 2024-10-11 10:19

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0029_tasknode_include_obsolete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='assigned_to_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Assign Task to'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Warning'), (2, 'Danger')], default=0, verbose_name='Task Priority'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='summary',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Task Summary'),
        ),
        migrations.CreateModel(
            name='WebDAVClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webdav_hostname', models.CharField(max_length=255)),
                ('webdav_login', models.CharField(max_length=50)),
                ('webdav_app_password', models.CharField(max_length=255)),
                ('webdav_path', models.CharField(blank=True, help_text='URL to replace: /remote.php/dav/files/KarrieCh/', max_length=255, null=True)),
                ('entry_path', models.CharField(blank=True, help_text='i.e. 02_Kommunikation/02_Presse', max_length=255, null=True)),
                ('local_path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path=models.CharField(blank=True, help_text='URL to replace: /remote.php/dav/files/KarrieCh/', max_length=255, null=True))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
