# Generated by Django 5.1.1 on 2024-10-11 12:38

import django.db.models.deletion
import gruene_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('filer', '0017_image__transparent'),
        ('gruene_cms', '0030_alter_taskitem_assigned_to_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdavclient',
            name='local_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path=gruene_cms.models.get_local_webdav_path),
        ),
        migrations.CreateModel(
            name='FolderNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('is_public', models.BooleanField(default=False)),
                ('ffolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.folder')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
