# Generated by Django 5.1.1 on 2024-10-11 13:38

import django.db.models.deletion
import gruene_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0031_alter_webdavclient_local_path_foldernode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFolderNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('local_path', models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path=gruene_cms.models.get_local_webdav_path)),
                ('is_public', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
