# Generated by Django 5.1.1 on 2024-10-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0032_localfoldernode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfoldernode',
            name='local_path',
        ),
        migrations.AddField(
            model_name='localfoldernode',
            name='webdav_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.webdavclient'),
            preserve_default=False,
        ),
    ]
