# Generated by Django 5.1.1 on 2024-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0034_localfoldernode_show_root_node_delete_foldernode'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfoldernode',
            name='extra_css_classes',
            field=models.CharField(default='folder-list small', max_length=255),
        ),
    ]
