# Generated by Django 5.1.1 on 2024-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gruene_cms', '0035_localfoldernode_extra_css_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdavclient',
            name='access_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
