# Generated by Django 5.1.1 on 2024-10-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0036_webdavclient_access_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='enable_for_auto_update',
            field=models.BooleanField(default=False, help_text='If checked, data source will be downloaded automatically'),
        ),
        migrations.AddField(
            model_name='newsfeedreader',
            name='enable_for_auto_update',
            field=models.BooleanField(default=False, help_text='If checked, news will be synced automatically'),
        ),
        migrations.AddField(
            model_name='webdavclient',
            name='enable_for_auto_update',
            field=models.BooleanField(default=False, help_text='If checked, folders will be synced automatically'),
        ),
    ]
