# Generated by Django 5.1.1 on 2024-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0037_datasource_enable_for_auto_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslistnode',
            name='show_feed_title',
            field=models.BooleanField(default=False),
        ),
    ]
