# Generated by Django 5.1.2 on 2024-10-20 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0039_newslistnode_extra_meta_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('div_classes', models.CharField(default='container', max_length=255)),
                ('extra_css_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_radial_bg_1', models.BooleanField(default=False)),
                ('enable_radial_bg_2', models.BooleanField(default=False)),
                ('enable_radial_bg_3', models.BooleanField(default=False)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
