# Generated by Django 5.1.2 on 2024-10-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0040_divnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMenuNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('include_home_page', models.BooleanField(default=False)),
                ('start_level', models.PositiveIntegerField(default=0)),
                ('extra_css_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('render_template', models.CharField(choices=[('as_p', 'As paragraphs'), ('as_ul', 'As ul, nested'), ('as_ul_flat', 'As ul, flat')], default='as_p', max_length=40)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
