# Generated by Django 5.1.2 on 2024-10-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0041_simplemenunode'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemenunode',
            name='extra_active',
            field=models.PositiveIntegerField(default=1, help_text='specifies how many levels of descendants of the currently active node should be displayed'),
        ),
        migrations.AddField(
            model_name='simplemenunode',
            name='extra_inactive',
            field=models.PositiveIntegerField(default=0, help_text='specifies how many levels of navigation should be displayed if a node is not a direct ancestor or descendant of the current active node'),
        ),
        migrations.AddField(
            model_name='simplemenunode',
            name='to_level',
            field=models.PositiveIntegerField(default=1, help_text='...and at which level it should stop'),
        ),
        migrations.AlterField(
            model_name='simplemenunode',
            name='render_template',
            field=models.CharField(choices=[('as_p', 'As paragraphs'), ('as_ul_nested', 'As ul, nested'), ('as_ul_flat', 'As ul, flat')], default='as_p', max_length=40),
        ),
        migrations.AlterField(
            model_name='simplemenunode',
            name='start_level',
            field=models.PositiveIntegerField(default=0, help_text='specify from which level the navigation should be rendered...'),
        ),
    ]
