# Generated by Django 5.1.2 on 2024-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0042_simplemenunode_extra_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemenunode',
            name='render_template',
            field=models.CharField(choices=[('as_p', 'As paragraphs'), ('as_ul_nested', 'As ul, nested'), ('as_ul_flat', 'As ul, flat'), ('as_nav_subpages', 'As nav, subpages, horizontal')], default='as_p', max_length=40),
        ),
    ]
