# Generated by Django 5.1.2 on 2024-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0043_alter_simplemenunode_render_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='newsfeedreader_external_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
