# Generated by Django 5.1.2 on 2024-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0045_alter_newslistnode_render_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslistnode',
            name='render_template',
            field=models.CharField(choices=[('tiles', 'Tiles, Image and Summary'), ('table', 'Table, Image and Summary'), ('card_v1', 'Cards, Variant 1, two cols'), ('card_v2', 'Cards, Variant 2, one col'), ('full', 'Full')], default='tiles', max_length=20),
        ),
    ]
