# Generated by Django 5.1.1 on 2024-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0047_webdavclient_entry_path_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='enable_masonry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newslistnode',
            name='extra_row_classes',
            field=models.CharField(blank=True, help_text='Example: "mb-3" or "g-5"', max_length=255, null=True),
        ),
    ]
