# Generated by Django 5.1.1 on 2024-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0048_newslistnode_enable_masonry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='show_category_image',
            field=models.BooleanField(default=False),
        ),
    ]
