# Generated by Django 5.1.1 on 2024-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0049_newslistnode_show_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistnode',
            name='col_config',
            field=models.CharField(blank=True, choices=[(None, 'All same width'), ('12,6,6', 'First 12, others 6/6 cols'), ('12,8,4', 'First 12, others 8/4 cols'), ('12,4,8', 'First 12, others 4/8 cols'), ('12,9,3', 'First 12, others 9/3 cols'), ('12,9,3', 'First 12, others 3/9 cols'), ('12,4,4,4,6', 'First 12, then 4/4/4 cols, others 6 cols')], max_length=15, null=True),
        ),
    ]
