# Generated by Django 5.1.1 on 2024-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0052_rename_col_config_newslistnode_col_lg_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
