# Generated by Django 5.1.2 on 2024-11-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0054_alter_webdavclient_force_mimetype_nextcloudaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='insert_images',
            field=models.CharField(choices=[('replace-marker', 'Replace Marker')], default='replace-marker', max_length=255),
        ),
        migrations.CreateModel(
            name='NextCloudCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_slug', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.nextcloudaccount')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.calendar')),
            ],
        ),
    ]
