# Generated by Django 5.1.2 on 2024-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0055_alter_newsitem_insert_images_nextcloudcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeedreader',
            name='active_auto_update',
            field=models.BooleanField(default=False),
        ),
    ]
