# Generated by Django 5.1.2 on 2024-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0057_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruenecmsanimatetypingnode',
            name='animation',
            field=models.CharField(choices=[('animatetyping', 'Animate Typing'), ('textscroll', 'Text Scroll')], default='animatetyping', max_length=20),
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='animated_text',
            field=models.CharField(help_text='Separated by |. i.e. "bla1|bla2|bla3"', max_length=500),
        ),
    ]
