# Generated by Django 5.1.2 on 2024-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0058_gruenecmsanimatetypingnode_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_animation_in',
            field=models.CharField(blank=True, help_text='See animate.css for options', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_animation_out',
            field=models.CharField(blank=True, help_text='See animate.css for options', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_speed',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_stoponhover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='animation',
            field=models.CharField(choices=[('animatetyping', 'Animate Typing'), ('wordsrotator', 'Wordsrotator')], default='animatetyping', max_length=20),
        ),
    ]
