# Generated by Django 5.1.2 on 2024-11-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0059_gruenecmsanimatetypingnode_wordsrotator_animation_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregateddata',
            options={'verbose_name': 'Data sources - aggregated data', 'verbose_name_plural': 'Data sources - aggregated data'},
        ),
        migrations.AlterModelOptions(
            name='aggregateddatahistory',
            options={'verbose_name': 'Data sources - aggregated data history', 'verbose_name_plural': 'Data sources - aggregated data histories'},
        ),
        migrations.AlterModelOptions(
            name='aggregateddatanode',
            options={'verbose_name': 'Data sources - aggregated data node', 'verbose_name_plural': 'Data sources - aggregated data nodes'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelOptions(
            name='calendaritem',
            options={'verbose_name': 'Calendar item', 'verbose_name_plural': 'Calendar items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'News category', 'verbose_name_plural': 'News categories'},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Data source', 'verbose_name_plural': 'Data sources'},
        ),
        migrations.AlterModelOptions(
            name='newsfeedreader',
            options={'verbose_name': 'Newsfeed reader', 'verbose_name_plural': 'Newsfeed readers'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'News image', 'verbose_name_plural': 'News images'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'verbose_name': 'News item', 'verbose_name_plural': 'News items'},
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='dt_from',
            field=models.DateTimeField(verbose_name='Event begin'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='dt_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event end'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='full_day',
            field=models.BooleanField(default=False, verbose_name='Full day'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='linked_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruene_cms.newsitem', verbose_name='Linked News'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Linked page'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='animation',
            field=models.CharField(choices=[('animatetyping', 'Animate Typing'), ('wordsrotator', 'Wordsrotator'), ('rotatingtext', "Rachel Smith's rotatingtext")], default='animatetyping', max_length=20),
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_animation_in',
            field=models.CharField(blank=True, help_text='See <a href="https://animate.style/">https://animate.style/</a> for options', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gruenecmsanimatetypingnode',
            name='wordsrotator_animation_out',
            field=models.CharField(blank=True, help_text='See <a href="https://animate.style/">https://animate.style/</a> for options', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newslistnode',
            name='news_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
    ]
