# Generated by Django 5.1.2 on 2024-11-26 11:56

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('gruene_cms', '0060_alter_aggregateddata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaritem',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.calendar', verbose_name='Calendar'),
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=5)),
                ('filefield', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.file')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruene_cms.newsitem')),
            ],
            options={
                'verbose_name': 'News attachment',
                'verbose_name_plural': 'News attachments',
            },
        ),
    ]
