# Generated by Django 5.1.2 on 2025-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0061_alter_calendaritem_calendar_newsattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfoldernode',
            name='entry_path',
            field=models.CharField(blank=True, help_text='i.e. 06_Sitzungsprotokolle/Steinweiler', max_length=255, null=True),
        ),
    ]
