# Generated by Django 5.1.2 on 2025-03-31 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('gruene_cms', '0062_localfoldernode_entry_path'),
        ('newsticker', '0002_alter_tickerref_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewstickerItemListNode',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('limit_days', models.IntegerField(default=3)),
                ('render_template', models.CharField(choices=[('default', 'Default')], max_length=40)),
                ('archive_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
                ('limit_categories', models.ManyToManyField(blank=True, to='newsticker.tickercategory')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
