# Generated by Django 5.1.2 on 2025-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0063_newstickeritemlistnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
