# Generated by Django 5.1.2 on 2025-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruene_cms', '0064_calendaritem_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaritem',
            name='external_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsfeedreader',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='newsfeedreader_external_image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='newsfeedreader_external_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
